title: Your awesome title
author: Kian
email: yijianhuang1989@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write code,blow minds.Here nice to meet you all guys~

# social links
weibo_username: MrOnej
github_username: Machine-01

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
